"""Platform adapter interfaces (documentation + typing helpers)."""

from __future__ import annotations

from typing import Protocol


class PlatformAdapter(Protocol):
    APP_ID: str
    LOCK_NAME: str

    def config_dir(self) -> str: ...
    def legacy_config_dir(self) -> str: ...
    def browser_processes(self) -> set[str]: ...
    def autostart_key(self) -> str: ...
    def open_path(self, path: str) -> None: ...
    def show_message(self, message: str, title: str, flags: int = 0) -> None: ...
    def set_app_user_model_id(self, app_id: str) -> None: ...
    def ensure_native_init(self) -> None: ...
